 /*  Resource C-Header-File v1.95 fÅr ResourceMaster ab v2.06 by ARDISOFT  */

#define MENU 0  /* menu */
#define MPROGRAMMINFO 9  /* STRING in tree MENU */
#define MOEFFNEPH 18  /* STRING in tree MENU */
#define MPHCLOSE 19  /* STRING in tree MENU */
#define MOEFFNEDBF 21  /* STRING in tree MENU */
#define MDBCLOSE 22  /* STRING in tree MENU */
#define MENDE 24  /* STRING in tree MENU */
#define MPHSTRUKTUR 26  /* STRING in tree MENU */
#define MDBASESTRUCT 28  /* STRING in tree MENU */
#define MDBASEDATEN 29  /* STRING in tree MENU */
#define MIMPORT 31  /* STRING in tree MENU */
#define MERZEUGEN 33  /* STRING in tree MENU */
#define MKEYTAB 35  /* STRING in tree MENU */
#define MFWECHSEL 37  /* STRING in tree MENU */
#define MFSCHLIESSEN 38  /* STRING in tree MENU */

#define DBASESTRUKMENU 1  /* menu */
#define DPROGRAMMINFO 7  /* STRING in tree DBASESTRUKMENU */
#define DEXPORTSTRUKT 9  /* STRING in tree DBASESTRUKMENU */
#define DDRUCKENSTRUKT 10  /* STRING in tree DBASESTRUKMENU */

#define PHOENIXSTRUKMENU 2  /* menu */
#define PPROGRAMMINFO 7  /* STRING in tree PHOENIXSTRUKMENU */
#define PEXPORTSTRUKT 9  /* STRING in tree PHOENIXSTRUKMENU */

#define COPYRIGHT 3  /* form/dial */
#define CPHOENIX 12  /* TEXT in tree COPYRIGHT */
#define CSYSGEM 9  /* TEXT in tree COPYRIGHT */
#define CVERSION 5  /* TEXT in tree COPYRIGHT */
#define COK 2  /* BUTTON in tree COPYRIGHT */
#define CDATUM 7  /* TEXT in tree COPYRIGHT */

#define MAIN 4  /* form/dial */
/* Phoenix Felder */
#define MPH 2  /* BOX in tree MAIN */
#define MPHUP 3  /* BOXCHAR in tree MAIN */
/* Importiert die dBASE-DatensÑtze in die Phoenix-Datenbank. */
#define MDOIMPORT 4  /* BUTTON in tree MAIN */
#define MPHVSLIDERBOX 5  /* BOX in tree MAIN */
#define MPHVSLIDER 6  /* BOX in tree MAIN */
#define MPHDOWN 7  /* BOXCHAR in tree MAIN */
#define MPHRIGHT 8  /* BOXCHAR in tree MAIN */
#define MPHLEFT 9  /* BOXCHAR in tree MAIN */
#define MPHHSLIDERBOX 10  /* BOX in tree MAIN */
#define MPHHSLIDER 11  /* BOX in tree MAIN */
/* Tabellen auswahl */
#define MPHTABELLEN 12  /* BOXTEXT in tree MAIN */
/* dBASE Felder */
#define MDB 13  /* BOX in tree MAIN */
#define MDBUP 14  /* BOXCHAR in tree MAIN */
#define MDBSLIDERBOX 15  /* BOX in tree MAIN */
#define MDBSLIDER 16  /* BOX in tree MAIN */
#define MDBDOWN 17  /* BOXCHAR in tree MAIN */
/* Verbindungsbox */
#define MIM 19  /* BOX in tree MAIN */
#define MIMUP 20  /* BOXCHAR in tree MAIN */
#define MIMSLIDERBOX 21  /* BOX in tree MAIN */
#define MIMSLIDER 22  /* BOX in tree MAIN */
#define MIMDOWN 23  /* BOXCHAR in tree MAIN */
/* Beendet den Dialog ohne die DatensÑtze zu importieren. */
#define MABBRUCH 24  /* BUTTON in tree MAIN */
/* Alle Felder zum verbinden. */
#define MPH_IMPORT_ALLE 25  /* BUTTON in tree MAIN */
/* Alle Felder aus der Verbindung lîsen. */
#define MIMPORT_PH_ALLE 26  /* BUTTON in tree MAIN */
/* Datentyp, Phoenix */
#define MPHTYP 29  /* STRING in tree MAIN */
/* LÑnge des des Datentyp, Phoenix */
#define MPHLAENGE 30  /* STRING in tree MAIN */
/* Datentyp, dBASE */
#define MDBTYP 31  /* STRING in tree MAIN */
/* LÑnge des Datentyp, dBASE */
#define MDBLAENGE 32  /* STRING in tree MAIN */
/* Alle Felder zum verbinden. */
#define MDB_IMPORT_ALLE 33  /* BUTTON in tree MAIN */
/* Alle Felder aus der Verbindung lîsen. */
#define MIMPORT_DB_ALLE 34  /* BUTTON in tree MAIN */
#define MIFELDERBOX 37  /* IBOX in tree MAIN */
/* Datentyp, Phoenix */
#define MPHITYP 38  /* STRING in tree MAIN */
/* LÑnge des des Datentyp, Phoenix */
#define MPHILAENGE 39  /* STRING in tree MAIN */
/* Datentyp, dBASE */
#define MDBITYP 40  /* STRING in tree MAIN */
/* LÑnge des Datentyp, dBASE */
#define MDBILAENGE 41  /* STRING in tree MAIN */
/* Das selektierte Feld zum verbinden. */
#define MDB_IMPORT 42  /* BUTTON in tree MAIN */
/* Selektiertes Feld aus der Verindung lîsen. */
#define MIMPORT_DB 43  /* BUTTON in tree MAIN */
/* Das selektierte Feld zum verbinden. */
#define MPH_IMPORT 44  /* BUTTON in tree MAIN */
/* Selektiertes Feld aus der Verindung lîsen. */
#define MIMPORT_PH 45  /* BUTTON in tree MAIN */

#define LOGIN 5  /* form/dial */
/* Benutzername eingeben */
#define LBENUTZER 3  /* FTEXT in tree LOGIN */
/* Verdeckte Passwort eingabe */
#define LPASSWORT 4  /* FTEXT in tree LOGIN */
/* Eingabe bestÑtigen */
#define LOK 5  /* BUTTON in tree LOGIN */
/* Eingabe abbrechen */
#define LABBRUCH 6  /* BUTTON in tree LOGIN */

#define DBASESTRUKTUR 6  /* form/dial */
#define DBLETZEAENDER 2  /* STRING in tree DBASESTRUKTUR */
#define DBASETYP 4  /* STRING in tree DBASESTRUKTUR */
#define DBSTBOX 8  /* BOX in tree DBASESTRUKTUR */
#define DBSTUP 9  /* BOXCHAR in tree DBASESTRUKTUR */
#define DBSTSLIDERBOX 10  /* BOX in tree DBASESTRUKTUR */
#define DBSTSLIDER 11  /* BOX in tree DBASESTRUKTUR */
#define DBSTDOWN 12  /* BOXCHAR in tree DBASESTRUKTUR */
#define DBSTOK 13  /* BUTTON in tree DBASESTRUKTUR */
#define DBSTGROESSE 17  /* STRING in tree DBASESTRUKTUR */
#define DBSTANZAHL 19  /* STRING in tree DBASESTRUKTUR */

#define PHOENIXSTRUKT 7  /* form/dial */
#define PHSTCREATED 3  /* STRING in tree PHOENIXSTRUKT */
#define PHSTLASTUSE 4  /* STRING in tree PHOENIXSTRUKT */
#define PHSTTABELLE 5  /* BOXTEXT in tree PHOENIXSTRUKT */
#define PHSTOK 7  /* BUTTON in tree PHOENIXSTRUKT */
#define PHSTTABELLENBOX 8  /* BUTTON in tree PHOENIXSTRUKT */
#define PHSTRECS 10  /* STRING in tree PHOENIXSTRUKT */
#define PHSTBOX 14  /* BOX in tree PHOENIXSTRUKT */
#define PHSTUP 15  /* BOXCHAR in tree PHOENIXSTRUKT */
#define PHSTSLIDERBOX 16  /* BOX in tree PHOENIXSTRUKT */
#define PHSTSLIDER 17  /* BOX in tree PHOENIXSTRUKT */
#define PHSTDOWN 18  /* BOXCHAR in tree PHOENIXSTRUKT */

#define EINSTELLUNGEN 8  /* form/dial */
#define GEDIMPKEYTABLIST 1  /* TEXT in tree EINSTELLUNGEN */
#define EINOK 3  /* BUTTON in tree EINSTELLUNGEN */
#define EINSETZEN 4  /* BUTTON in tree EINSTELLUNGEN */
#define EINABBRUCH 5  /* BUTTON in tree EINSTELLUNGEN */
#define EINNUMZAHL 7  /* BUTTON in tree EINSTELLUNGEN */
#define EINNUMLANGZAHL 8  /* BUTTON in tree EINSTELLUNGEN */
#define EINNUMFLIESS 9  /* BUTTON in tree EINSTELLUNGEN */
#define EINLOGISCHZAHL 11  /* BUTTON in tree EINSTELLUNGEN */
#define EINLOGISCHTEXT 12  /* BUTTON in tree EINSTELLUNGEN */

#define KEYTAB 9  /* form/dial */
#define KEYTABIMABBRUCH 1  /* BUTTON in tree KEYTAB */
#define KEYTABIMPOK 2  /* BUTTON in tree KEYTAB */
#define KEYTABLIST 3  /* TEXT in tree KEYTAB */

#define PRN_SUB 10  /* form/dial */
#define PS_GFNAME 2  /* TEXT in tree PRN_SUB */
#define PS_GFPTS 3  /* STRING in tree PRN_SUB */
#define PS_GFSEL 5  /* BUTTON in tree PRN_SUB */
#define PS_RANDLEN 7  /* FTEXT in tree PRN_SUB */

#define PRN_ICON 11  /* form/dial */
#define WD_01 1  /* ICON in tree PRN_ICON */

#define TEXTE 12  /* form/dial */
#define TEXT_000 1  /* STRING in tree TEXTE */
#define TEXT_001 2  /* STRING in tree TEXTE */
#define TEXT_002 3  /* STRING in tree TEXTE */
#define TEXT_003 4  /* STRING in tree TEXTE */
#define TEXT_004 5  /* STRING in tree TEXTE */
#define TEXT_005 6  /* STRING in tree TEXTE */
#define TEXT_006 7  /* STRING in tree TEXTE */
#define TEXT_007 8  /* STRING in tree TEXTE */
#define TEXT_008 9  /* STRING in tree TEXTE */
#define TEXT_009 10  /* STRING in tree TEXTE */
#define TEXT_010 11  /* STRING in tree TEXTE */
#define TEXT_011 12  /* STRING in tree TEXTE */
#define TEXT_012 13  /* STRING in tree TEXTE */
#define TEXT_013 14  /* STRING in tree TEXTE */
#define TEXT_014 15  /* STRING in tree TEXTE */
#define TEXT_015 16  /* STRING in tree TEXTE */
#define TEXT_016 17  /* STRING in tree TEXTE */
#define TEXT_017 18  /* STRING in tree TEXTE */
#define TEXT_018 19  /* STRING in tree TEXTE */
#define TEXT_019 20  /* STRING in tree TEXTE */
#define TEXT_027 21  /* STRING in tree TEXTE */
#define TEXT_020 22  /* STRING in tree TEXTE */
#define TEXT_021 23  /* STRING in tree TEXTE */
#define TEXT_022 24  /* STRING in tree TEXTE */
#define TEXT_023 25  /* STRING in tree TEXTE */
#define TEXT_024 26  /* STRING in tree TEXTE */
#define TEXT_025 27  /* STRING in tree TEXTE */
#define TEXT_046 42  /* STRING in tree TEXTE */
#define TEXT_026 43  /* STRING in tree TEXTE */
#define TEXT_028 44  /* STRING in tree TEXTE */
#define TEXT_029 45  /* STRING in tree TEXTE */
#define TEXT_030 46  /* STRING in tree TEXTE */

#define PHOENIX_BASE 13  /* form/dial */
#define ERROR_00 1  /* STRING in tree PHOENIX_BASE */
#define ERROR_40 41  /* STRING in tree PHOENIX_BASE */
#define TEXT_01 42  /* STRING in tree PHOENIX_BASE */
#define TEXT_02 43  /* STRING in tree PHOENIX_BASE */
#define MONAT_KURZ_01 44  /* STRING in tree PHOENIX_BASE */
#define MONAT_KURZ_12 55  /* STRING in tree PHOENIX_BASE */
#define MONAT_LANG_01 56  /* STRING in tree PHOENIX_BASE */
#define MONAT_LANG_12 67  /* STRING in tree PHOENIX_BASE */

#define ANLEITUNGS_TEXTE 14  /* form/dial */
#define HELP_000 3  /* STRING in tree ANLEITUNGS_TEXTE */
#define HELP_001 4  /* STRING in tree ANLEITUNGS_TEXTE */
#define HELP_002 5  /* STRING in tree ANLEITUNGS_TEXTE */
#define HELP_003 6  /* STRING in tree ANLEITUNGS_TEXTE */
#define HELP_004 7  /* STRING in tree ANLEITUNGS_TEXTE */
#define HELP_005 8  /* STRING in tree ANLEITUNGS_TEXTE */
#define HELP_006 9  /* STRING in tree ANLEITUNGS_TEXTE */

#define DBASE_LESE_FEHLER 0  /* Alert string */

#define DBASE_FORMAT 1  /* Alert string */

#define KEIN_SPEICHER 2  /* Alert string */

#define DBASE_DATEI_VORHANDEN 3  /* Alert string */

#define DATEI_ERZEUGEN 4  /* Alert string */

#define KEYTAB_NICHT_DA 5  /* Alert string */

#define DEFEKTE_INF 6  /* Alert string */

#define PFAD_FEHLER 7  /* Alert string */

#define DATEINAME_FEHLER 8  /* Alert string */

#define UNVOLLSTAENDIG 9  /* Alert string */

#define FEHLER_NULL_SETZEN 10  /* Alert string */

#define FEHLER_EINFUEGEN_FELD 11  /* Alert string */
