/* Resource Datei Indizes fÅr DB2PH */

#define MENU             0   /* Menuebaum */
#define MPROGRAMMINFO    9   /* STRING in Baum MENU */
#define MOEFFNEPH        18  /* STRING in Baum MENU */
#define MPHCLOSE         19  /* STRING in Baum MENU */
#define MOEFFNEDBF       21  /* STRING in Baum MENU */
#define MDBCLOSE         22  /* STRING in Baum MENU */
#define MENDE            24  /* STRING in Baum MENU */
#define MPHSTRUKTUR      26  /* STRING in Baum MENU */
#define MDBASESTRUCT     28  /* STRING in Baum MENU */
#define MDBASEDATEN      29  /* STRING in Baum MENU */
#define MIMPORT          31  /* STRING in Baum MENU */
#define MERZEUGEN        33  /* STRING in Baum MENU */
#define MKEYTAB          35  /* STRING in Baum MENU */
#define MFWECHSEL        37  /* STRING in Baum MENU */
#define MFSCHLIESSEN     38  /* STRING in Baum MENU */

#define DBASESTRUKMENU   1   /* Menuebaum */
#define DPROGRAMMINFO    7   /* STRING in Baum DBASESTRUKMENU */
#define DEXPORTSTRUKT    9   /* STRING in Baum DBASESTRUKMENU */

#define PHOENIXSTRUKMENU 2   /* Menuebaum */
#define PPROGRAMMINFO    7   /* STRING in Baum PHOENIXSTRUKMENU */
#define PEXPORTSTRUKT    9   /* STRING in Baum PHOENIXSTRUKMENU */

#define COPYRIGHT        3   /* Formular/Dialog */
#define COK              2   /* BUTTON in Baum COPYRIGHT */
#define CVERSION         5   /* TEXT in Baum COPYRIGHT */
#define CDATUM           7   /* TEXT in Baum COPYRIGHT */
#define CSYSGEM          9   /* TEXT in Baum COPYRIGHT */
#define CPHOENIX         12  /* TEXT in Baum COPYRIGHT */

#define MAIN             4   /* Formular/Dialog */
#define MPH              2   /* BOX in Baum MAIN */
#define MPHUP            3   /* BOXCHAR in Baum MAIN */
#define MDOIMPORT        4   /* BUTTON in Baum MAIN */
#define MPHVSLIDERBOX    5   /* BOX in Baum MAIN */
#define MPHVSLIDER       6   /* BOX in Baum MAIN */
#define MPHDOWN          7   /* BOXCHAR in Baum MAIN */
#define MPHRIGHT         8   /* BOXCHAR in Baum MAIN */
#define MPHLEFT          9   /* BOXCHAR in Baum MAIN */
#define MPHHSLIDERBOX    10  /* BOX in Baum MAIN */
#define MPHHSLIDER       11  /* BOX in Baum MAIN */
#define MPHTABELLEN      12  /* BOXTEXT in Baum MAIN */
#define MDB              13  /* BOX in Baum MAIN */
#define MDBUP            14  /* BOXCHAR in Baum MAIN */
#define MDBSLIDERBOX     15  /* BOX in Baum MAIN */
#define MDBSLIDER        16  /* BOX in Baum MAIN */
#define MDBDOWN          17  /* BOXCHAR in Baum MAIN */
#define MIM              19  /* BOX in Baum MAIN */
#define MIMUP            20  /* BOXCHAR in Baum MAIN */
#define MIMSLIDERBOX     21  /* BOX in Baum MAIN */
#define MIMSLIDER        22  /* BOX in Baum MAIN */
#define MIMDOWN          23  /* BOXCHAR in Baum MAIN */
#define MABBRUCH         24  /* BUTTON in Baum MAIN */
#define MPH_IMPORT_ALLE  25  /* BUTTON in Baum MAIN */
#define MIMPORT_PH_ALLE  26  /* BUTTON in Baum MAIN */
#define MPHTYP           29  /* STRING in Baum MAIN */
#define MPHLAENGE        30  /* STRING in Baum MAIN */
#define MDBTYP           31  /* STRING in Baum MAIN */
#define MDBLAENGE        32  /* STRING in Baum MAIN */
#define MDB_IMPORT_ALLE  33  /* BUTTON in Baum MAIN */
#define MIMPORT_DB_ALLE  34  /* BUTTON in Baum MAIN */
#define MIFELDERBOX      37  /* IBOX in Baum MAIN */
#define MPHITYP          38  /* STRING in Baum MAIN */
#define MPHILAENGE       39  /* STRING in Baum MAIN */
#define MDBITYP          40  /* STRING in Baum MAIN */
#define MDBILAENGE       41  /* STRING in Baum MAIN */
#define MDB_IMPORT       42  /* BUTTON in Baum MAIN */
#define MIMPORT_DB       43  /* BUTTON in Baum MAIN */
#define MPH_IMPORT       44  /* BUTTON in Baum MAIN */
#define MIMPORT_PH       45  /* BUTTON in Baum MAIN */

#define LOGIN            5   /* Formular/Dialog */
#define LBENUTZER        3   /* FTEXT in Baum LOGIN */
#define LPASSWORT        4   /* FTEXT in Baum LOGIN */
#define LOK              5   /* BUTTON in Baum LOGIN */
#define LABBRUCH         6   /* BUTTON in Baum LOGIN */

#define DBASESTRUKTUR    6   /* Formular/Dialog */
#define DBLETZEAENDER    2   /* STRING in Baum DBASESTRUKTUR */
#define DBASETYP         4   /* STRING in Baum DBASESTRUKTUR */
#define DBSTBOX          8   /* BOX in Baum DBASESTRUKTUR */
#define DBSTUP           9   /* BOXCHAR in Baum DBASESTRUKTUR */
#define DBSTSLIDERBOX    10  /* BOX in Baum DBASESTRUKTUR */
#define DBSTSLIDER       11  /* BOX in Baum DBASESTRUKTUR */
#define DBSTDOWN         12  /* BOXCHAR in Baum DBASESTRUKTUR */
#define DBSTOK           13  /* BUTTON in Baum DBASESTRUKTUR */
#define DBSTGROESSE      17  /* STRING in Baum DBASESTRUKTUR */
#define DBSTANZAHL       19  /* STRING in Baum DBASESTRUKTUR */

#define PHOENIXSTRUKT    7   /* Formular/Dialog */
#define PHSTCREATED      3   /* STRING in Baum PHOENIXSTRUKT */
#define PHSTLASTUSE      4   /* STRING in Baum PHOENIXSTRUKT */
#define PHSTTABELLE      5   /* BOXTEXT in Baum PHOENIXSTRUKT */
#define PHSTOK           7   /* BUTTON in Baum PHOENIXSTRUKT */
#define PHSTTABELLENBOX  8   /* BUTTON in Baum PHOENIXSTRUKT */
#define PHSTRECS         10  /* STRING in Baum PHOENIXSTRUKT */
#define PHSTBOX          14  /* BOX in Baum PHOENIXSTRUKT */
#define PHSTUP           15  /* BOXCHAR in Baum PHOENIXSTRUKT */
#define PHSTSLIDERBOX    16  /* BOX in Baum PHOENIXSTRUKT */
#define PHSTSLIDER       17  /* BOX in Baum PHOENIXSTRUKT */
#define PHSTDOWN         18  /* BOXCHAR in Baum PHOENIXSTRUKT */

#define EINSTELLUNGEN    8   /* Formular/Dialog */
#define GEDIMPKEYTABLIST 1   /* TEXT in Baum EINSTELLUNGEN */
#define EINOK            3   /* BUTTON in Baum EINSTELLUNGEN */
#define EINSETZEN        4   /* BUTTON in Baum EINSTELLUNGEN */
#define EINABBRUCH       5   /* BUTTON in Baum EINSTELLUNGEN */
#define EINNUMZAHL       7   /* BUTTON in Baum EINSTELLUNGEN */
#define EINNUMLANGZAHL   8   /* BUTTON in Baum EINSTELLUNGEN */
#define EINNUMFLIESS     9   /* BUTTON in Baum EINSTELLUNGEN */
#define EINLOGISCHZAHL   11  /* BUTTON in Baum EINSTELLUNGEN */
#define EINLOGISCHTEXT   12  /* BUTTON in Baum EINSTELLUNGEN */

#define KEYTAB           9   /* Formular/Dialog */
#define KEYTABIMABBRUCH  1   /* BUTTON in Baum KEYTAB */
#define KEYTABIMPOK      2   /* BUTTON in Baum KEYTAB */
#define KEYTABLIST       3   /* TEXT in Baum KEYTAB */

#define PRN_SUB          10  /* Formular/Dialog */
#define PS_GFNAME        2   /* TEXT in Baum PRN_SUB */
#define PS_GFPTS         3   /* STRING in Baum PRN_SUB */
#define PS_GFSEL         5   /* BUTTON in Baum PRN_SUB */
#define PS_RANDLEN       7   /* FTEXT in Baum PRN_SUB */

#define PRN_ICON         11  /* Formular/Dialog */
#define WD_01            1   /* ICON in Baum PRN_ICON */
