/*
 * this file belongs to 'xhex' and is published under the
 * GNU General Public License (GPL), see COPYING for details.
 *
 * (c) rasca gmelch, berlin 1995, 1996
 */

#ifdef GERMAN
#define M_FILE	"Datei"
#define M_LOAD	"Datei öffnen .."
#define M_SAVE	"Speichern unter .."
#define M_QUIT	"Beenden"
#define M_HEX	"Hexadezimal"
#define M_DEC	"Dezimal"
#define M_OCT	"Oktal"
#define B_ABOUT	"Über .."
#define L_NO_FILE	"   <keine Datei>                       "
#define MSG_NO_DBASE_FILE	"Die Datei ist keine xBase-Datei, stimmt's?\n"
#define MSG_CANT_OPEN_FILE	"Datei kann nicht geöffnet werden!\n"
#define MSG_UNKNOWN_MODE	"unbekannter Modus!\n"
#define MSG_FILE			"Datei"
#define MSG_SIZE			"Größe"
#define MSG_PLEASE_WAIT		"bitte warten .."
#else
#define M_FILE	"File"
#define M_LOAD	"Load .."
#define M_SAVE	"Save as .."
#define M_QUIT	"Quit"
#define M_HEX	"Hexadecimal"
#define M_DEC	"Decimal"
#define M_OCT	"Octal"
#define B_ABOUT	"About"
#define L_NO_FILE	"   <no file>                           "
#define MSG_NO_DBASE_FILE	"it's not a xbase file, isn't it?\n"
#define MSG_CANT_OPEN_FILE	"can't open file\n"
#define MSG_UNKNOWN_MODE	"unknown mode!\n"
#define MSG_FILE			"file"
#define MSG_SIZE			"size"
#define MSG_PLEASE_WAIT		"please wait .."
#endif

