/*****************************************************************************/
/*                                                                           */
/* Modul: PHOENIX.H                                                          */
/* Datum: 19/06/91                                                           */
/*                                                                           */
/*****************************************************************************/

#ifndef __PHOENIX__
#define __PHOENIX__

#include "conv.h"
#include "files.h"
#include "utility.h"
#include "dbcall.h"
#include "dbcalc.h"

#endif /* __PHOENIX__ */
